# Generated by Django 5.0.7 on 2024-07-31 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='flights.airport'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('route', 'airplane', 'departure_time', 'arrival_time')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'row', 'seat')},
        ),
    ]
