# Generated by Django 5.0.7 on 2024-08-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_airplanetype_name_alter_airport_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
    ]
