# Generated by Django 5.0.7 on 2024-08-02 13:12

import flights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_route_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=flights.models.airplane_image_file_path),
        ),
    ]
