# Generated by Django 5.0.7 on 2024-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_airplane_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
